api:
  build: .
  dockerfile: ./docker/Dockerfile-dev
  volumes:
    - ./:/app/
  working_dir: /app/
  ports:
    - "9000:9000"
  privileged: true
  environment:
    - DEBUG=true
    - PROJECT_PROPERTIES=project-properties.json
