FROM artifactory.allegrogroup.com/pylabs/alle-swift-dev:4.2-2-ubuntu16

ENV PROJECT_PATH /opt/swiftbox
WORKDIR $PROJECT_PATH

RUN set -ex \
    && apt-get update \
    && apt-get install -y apt-transport-https zip wget software-properties-common \
    && wget -q https://repo.vapor.codes/apt/keyring.gpg -O- | apt-key add - \
    && echo "deb https://repo.vapor.codes/apt $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/vapor.list \
    && apt-get update \
    && apt-get install -y vapor
